---
version: "3.7"
services:
  teamspeak:
    image: teamspeak
    container_name: teamspeak-service
    depends_on:
      - db
    restart: always
    ports:
      - 9987:9987/udp
      - 10011:10011
      - 30033:30033
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: $TEAMSPEAK_DB_PASSWORD
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    volumes:
      - service-volume:/var/ts3server
    healthcheck:
      test: [ "CMD-SHELL", "netstat -an | grep 30033 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;" ]
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 20s
  db:
    image: mariadb
    container_name: teamspeak-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $TEAMSPEAK_DB_PASSWORD
      MYSQL_DATABASE: teamspeak
    volumes:
      - db-volume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 20s
volumes:
  service-volume:
    external: false
  db-volume:
    external: false
