---
version: "3.7"
services:
  teamspeak:
    image: teamspeak
    container_name: teamspeak-service
    depends_on:
      - db
    restart: always
    environment:
      TS3SERVER_DB_PLUGIN: ts3db_mariadb
      TS3SERVER_DB_SQLCREATEPATH: create_mariadb
      TS3SERVER_DB_HOST: db
      TS3SERVER_DB_USER: root
      TS3SERVER_DB_PASSWORD: $TEAMSPEAK_DB_PASSWORD
      TS3SERVER_DB_NAME: teamspeak
      TS3SERVER_DB_WAITUNTILREADY: 30
      TS3SERVER_LICENSE: accept
    labels:
      - "traefik.enable=true"
      - "traefik.udp.services.teamspeak.loadbalancer.server.port=9987"
      - "traefik.udp.routers.teamspeak.entrypoints=ts-streaming"
      - "traefik.tcp.services.teamspeak-serverquery.loadbalancer.server.port=10011"
      - "traefik.tcp.routers.teamspeak-serverquery.service=teamspeak-serverquery"
      - "traefik.tcp.routers.teamspeak-serverquery.entrypoints=ts-serverquery"
      - "traefik.tcp.routers.teamspeak-serverquery.rule=Host(`${TS_FQDN}`)"
      - "traefik.tcp.services.ts-filetransfer.loadbalancer.server.port=30033"
      - "traefik.tcp.routers.ts-filetransfer.service=ts-filetransfer"
      - "traefik.tcp.routers.ts-filetransfer.entrypoints=ts-filetransfer"
      - "traefik.tcp.routers.ts-filetransfer.rule=Host(`${TS_FQDN}`)"
    healthcheck:
      test: [ "CMD-SHELL", "netstat -an | grep 30033 > /dev/null; if [ 0 != $$? ]; then exit 1; fi;" ]
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 20s
    volumes:
      - service-volume:/var/ts3server
    networks:
      - traefik_proxy
      - default
  db:
    image: mariadb
    container_name: teamspeak-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: $TEAMSPEAK_DB_PASSWORD
      MYSQL_DATABASE: teamspeak
    volumes:
      - db-volume:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "--silent" ]
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 20s
    networks:
      - default
volumes:
  service-volume:
    external: false
  db-volume:
    external: false
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
