version: 2.1
jobs:
  deploy:
    docker:
      - image: circleci/buildpack-deps
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b0:34:23:80:ce:a2:6d:59:f5:10:f3:a5:d3:a8:0b:80"
      - run:
          name: Add Endpoint to known hosts
          command: ssh-keyscan -t rsa $REMOTE_HOST > ~/.ssh/known_hosts
      - checkout
      - run:
          name: Pull & checkout code
          command: |
            ssh $REMOTE_HOST " \
              cd ~ &&\
              git clone https://github.com/kirintwn/homelab.git 2> /dev/null || git -C homelab checkout master && git -C homelab pull &&\
              git -C homelab checkout ${CIRCLE_SHA1}
            "
      - run:
          name: Create necessary resources
          command: |
            ssh $REMOTE_HOST " \
              [ -s ~/homelab/traefik/config/ACME/acme.json ] || cp ~/acme.json ~/homelab/traefik/config/ACME/acme.json &&\
              chmod 600 ~/homelab/traefik/config/ACME/acme.json &&\
              stat ~/homelab/traefik/config/ACME/acme.json &&\
              docker network inspect traefik_proxy >/dev/null 2>&1 || docker network create traefik_proxy \
            "
      - run:
          name: Deploy traefik
          command: |
            ssh $REMOTE_HOST " \
              export TRAEFIK_FQDN=${TRAEFIK_FQDN} &&\
              export TRAEFIK_PROVIDERS_GOOGLE_CLIENT_ID=${TRAEFIK_PROVIDERS_GOOGLE_CLIENT_ID} &&\
              export TRAEFIK_PROVIDERS_GOOGLE_CLIENT_SECRET=${TRAEFIK_PROVIDERS_GOOGLE_CLIENT_SECRET} &&\
              export TRAEFIK_PROVIDERS_OIDC_ISSUER_URL=${TRAEFIK_PROVIDERS_OIDC_ISSUER_URL} &&\
              export TRAEFIK_AUTH_SECRET=${TRAEFIK_AUTH_SECRET} &&\
              export TRAEFIK_AUTH_WHITELIST_EMAIL=${TRAEFIK_AUTH_WHITELIST_EMAIL} &&\
              export TRAEFIK_AUTH_FQDN=${TRAEFIK_AUTH_FQDN} &&\
              cd ~/homelab/traefik && docker-compose up --build -V -d \
            "
      - run:
          name: Deploy portainer
          command: |
            ssh $REMOTE_HOST " \
              export PORTAINER_FQDN=${PORTAINER_FQDN} &&\
              cd ~/homelab/portainer && docker-compose up --build -d \
            "
      - run:
          name: Deploy adguard-home
          command: |
            ssh $REMOTE_HOST " \
              export DNS_FQDN=${DNS_FQDN} &&\
              cd ~/homelab/adguard-home && sudo -E docker-compose up --build -V -d \
            "
      - run:
          name: Deploy teamspeak
          command: |
            ssh $REMOTE_HOST " \
              export TEAMSPEAK_DB_PASSWORD=${TEAMSPEAK_DB_PASSWORD} &&\
              cd ~/homelab/teamspeak && docker-compose up --build -d \
            "
      - run:
          name: Deploy docker-autoheal
          command: |
            ssh $REMOTE_HOST " \
              cd ~/homelab/docker-autoheal && docker-compose up --build -d \
            "
      - run:
          name: Check all containers
          command: |
            ssh $REMOTE_HOST "docker ps"
      - run:
          name: Reset to master/HEAD
          command: |
            ssh $REMOTE_HOST "git -C homelab checkout master"
workflows:
  main:
    jobs:
      - deploy:
          filters:
            branches:
              only:
                - master
