---
version: '3.7'

services:
  traefik:
    image: traefik
    container_name: traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/config:/etc/traefik
    ports:
      - "80:80"
      - "443:443"
    restart: always
    labels:
      - "traefik.enable=true"
      # Middleware - Forward Auth (Google OAUTH2)
      - "traefik.http.middlewares.traefik-google-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-google-auth.forwardauth.trustForwardHeader=true"
      - "traefik.http.middlewares.traefik-google-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      # Middleware - HTTP To HTTPS Redirect
      - "traefik.http.middlewares.https-redirect.redirectscheme.scheme=https"
      # Router - All HTTP To HTTPS Redirect
      - "traefik.http.routers.https-redirect.entrypoints=http"
      - "traefik.http.routers.https-redirect.rule=HostRegexp(`{any:.*}`)"
      - "traefik.http.routers.https-redirect.middlewares=https-redirect"
      # Dashboard Service Config
      - "traefik.http.routers.api.entrypoints=http,https"
      - "traefik.http.routers.api.rule=Host(`${TRAEFIK_FQDN}`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"
      - "traefik.http.routers.api.middlewares=traefik-google-auth"
    healthcheck:
      test: traefik healthcheck
      interval: 30s
      timeout: 5s
      retries: 1
      start_period: 10s
    networks:
      - traefik_proxy
      - default
  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth
    container_name: traefik-forward-auth
    environment:
      - PROVIDERS_GOOGLE_CLIENT_ID=$TRAEFIK_PROVIDERS_GOOGLE_CLIENT_ID
      - PROVIDERS_GOOGLE_CLIENT_SECRET=$TRAEFIK_PROVIDERS_GOOGLE_CLIENT_SECRET
      - PROVIDERS_OIDC_ISSUER_URL=$TRAEFIK_PROVIDERS_OIDC_ISSUER_URL
      - SECRET=$TRAEFIK_AUTH_SECRET
      - WHITELIST=$TRAEFIK_AUTH_WHITELIST_EMAIL
    networks:
      - traefik_proxy
      - default
  traefik-bastion:
    image: ubuntu:latest
    container_name: traefik-bastion
    command: "tail -f /dev/null"
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "exit 0" ]
      interval: 60s
      timeout: 5s
      retries: 1
      start_period: 30s
    networks:
      - traefik_proxy
      - default
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
