[log]
  level = "ERROR"

[providers]
  [providers.docker]
    endpoint = "unix:///var/run/docker.sock"
    network = "traefik_proxy"
    watch = true
    exposedbydefault = false

[accessLog]
  [accessLog.filters]
    statusCodes = ["400-499", "500-599"]

[api]
  dashboard = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"
  [entryPoints.ping]
    address = ":8082"
  [entryPoints.ts-streaming]
    address = ":9987/udp"
  [entryPoints.ts-serverquery]
    address = ":10011"
  [entryPoints.ts-filetransfer]
    address = ":30033"

[ping]
  entryPoint = "ping"

[certificatesResolvers]
  [certificatesResolvers.myresolver.acme]
    email = "kirintw@kirintw.app"
    storage = "/etc/traefik/ACME/acme.json"
    [certificatesResolvers.myresolver.acme.tlsChallenge]
