---
version: "3.7"
services:
  portainer:
    image: crazymax/diun
    container_name: diun
    restart: always
    environment:
      TZ: Asia/Taipei
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $PWD/config/diun.yml:/diun.yml:ro
      - data-volume:/data
volumes:
  data-volume:
    external: false
