---
version: "3.7"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguard-home
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=3000"
      - "traefik.http.routers.adguardhome.entrypoints=web,web-secure"
      - "traefik.http.routers.adguardhome.rule=Host(`${DNS_FQDN}`)"
      - "traefik.http.routers.adguardhome.tls=true"
      - "traefik.http.routers.adguardhome.tls.certresolver=myresolver"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 1.1.1.1
    volumes:
      - adguard-home-work-volume:/opt/adguardhome/work
      - adguard-home-conf-volume:/opt/adguardhome/conf
    networks:
      - traefik_proxy
      - default
volumes:
  adguard-home-work-volume:
    external: false
  adguard-home-conf-volume:
    external: false
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
