---
version: "3.7"
services:
  adguardhome:
    image: adguard/adguardhome
    container_name: adguard-home
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.adguardhome.loadbalancer.server.port=80"
      - "traefik.http.services.adguardhome.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.adguardhome.loadbalancer.healthcheck.interval=10s"
      - "traefik.http.services.adguardhome.loadbalancer.healthcheck.timeout=3s"
      - "traefik.http.routers.adguardhome.entrypoints=http,https"
      - "traefik.http.routers.adguardhome.rule=Host(`dns.${TLD}`)"
      - "traefik.http.routers.adguardhome.tls=true"
      - "traefik.http.routers.adguardhome.tls.certresolver=myresolver"
      - "traefik.http.routers.adguardhome.middlewares=traefik-google-auth"
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 853:853/tcp
    cap_add:
      - NET_ADMIN
    dns:
      - 127.0.0.1
      - 8.8.8.8
      - 1.1.1.1
    healthcheck:
      test: [ "CMD-SHELL", "nslookup a.root-servers.net 127.0.0.1 || exit 1" ]
      interval: 60s
      timeout: 5s
      retries: 1
      start_period: 30s
    volumes:
      - work-volume:/opt/adguardhome/work
      - conf-volume:/opt/adguardhome/conf
    networks:
      - traefik_proxy
      - default
volumes:
  work-volume:
    external: false
  conf-volume:
    external: false
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
