---
version: "3.7"
services:
  portainer:
    image: kirintwn/snapserver
    container_name: snapserver
    command: "--stream.stream=spotify:///librespot?name=spotify&username=${SPOTIFY_USERNAME}&password=${SPOTIFY_PASSWORD}"
    environment:
      TZ: Asia/Taipei
    restart: always
    ports:
      - "1704:1704"
      - "1705:1705"
      - "1780:1780"
