---
version: "3.7"
services:
  portainer:
    image: portainer/portainer
    container_name: portainer
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.entrypoints=http,https"
      - "traefik.http.routers.portainer.rule=Host(`${PORTAINER_FQDN}`)"
      - "traefik.http.routers.portainer.tls=true"
      - "traefik.http.routers.portainer.tls.certresolver=myresolver"
      - "traefik.http.routers.portainer.middlewares=traefik-forward-auth@file"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-volume:/data
    networks:
      - traefik_proxy
      - default
volumes:
  portainer-volume:
    external: false
networks:
  traefik_proxy:
    external:
      name: traefik_proxy
  default:
    driver: bridge
