---
version: "3.7"
services:
  autoheal:
    image: willfarrell/autoheal
    container_name: docker-autoheal
    restart: always
    environment:
      AUTOHEAL_CONTAINER_LABEL: all
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
